// <auto-generated />
namespace EmployeeListDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_create_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_create_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202110082116294_mig_create_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
